# Bitwise Majority Alignment

# Main BMA Algorithm

In [1]:
import numpy as np
import random
import csv
import time
import math

In [2]:
def bmaByCode(receivedStringArray):
    noOfStrings, length = receivedStringArray.shape
    
    c = np.zeros(noOfStrings,dtype=int)
    transmittedString = np.zeros(length,dtype=int)
    
    for i in range(length):
        temp = [0,0]
        for j in range(noOfStrings):
            tmp = receivedStringArray[j,c[j]]
            temp[tmp] += 1
        index_max = np.argmax(temp)
        transmittedString[i] = index_max  
        
        for j in range(noOfStrings):
            temp = c[j]
            for k in range(temp+1,length):
                if(receivedStringArray[j,k] == index_max):
                    c[j] = k
                    break
                c[j] = length-1
            
                  

    return transmittedString

In [3]:
def bma(receivedStringArray):
    noOfStrings, length = receivedStringArray.shape
    
    c = np.zeros(noOfStrings,dtype=int)
    transmittedString = np.zeros(length,dtype=int)
    
    for i in range(length):
        temp = [0,0]
        for j in range(noOfStrings):
            tmp = receivedStringArray[j,c[j]]
            temp[tmp] += 1
        index_max = np.argmax(temp)
        transmittedString[i] = index_max  
        
        for j in range(noOfStrings):
            if receivedStringArray[j,c[j]] == transmittedString[i]:
                c[j] += 1
            else:
                continue
            
                  

    return transmittedString

In [4]:
#For Testing

print(bma(np.array([[1,1,1,1],[1,1,1,0],[1,1,1,1]])))

[1 1 1 1]


# Dataset Generation

In [5]:
def createDataset(length, noOfTransmissions, prob):
    transmittedString = np.zeros(length,dtype=int)
    matrix = np.zeros((noOfTransmissions,length),dtype=int)
    
    for i in range(length):
        transmittedString[i] = random.randint(0,1)
    
    for k in range(noOfTransmissions):
        temp = np.zeros(length,dtype=int)
        j = 0
        for i in range(length):
            a = random.choices([0,1], weights=(prob,100-prob), k=1)
            if(a == [0]):
                continue
            else:
                temp[j] = transmittedString[i]
                j += 1
        matrix[k] = temp
    
    return transmittedString, matrix

In [6]:
correctString, generatedDataset = createDataset(5,10,10)
calculatedString = bma(np.array(generatedDataset))
   
print('Original String: {}\nGenerated Matrix:\n {}\nCalculated String: {}'.format(correctString,  generatedDataset, calculatedString))

Original String: [1 1 1 1 0]
Generated Matrix:
 [[1 1 1 1 0]
 [1 1 0 0 0]
 [1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 0 0 0]
 [1 1 1 1 0]
 [1 1 1 1 0]]
Calculated String: [1 1 1 1 0]


# Validation of the Algorithm

In [7]:
# prob_pool = [0.01, 0.03, 0.1, 0.3, 1.0, 3.0, 10.0, 30.0]

# header = ['Length', 'No. of Transmits', 'Deletion Probability', 'Percentage Error', 'Time Taken']

# file = 'BMA Results.csv'

# with open(file, 'w',newline='') as csvfile:
#     csvwriter = csv.writer(csvfile)
#     csvwriter.writerow(header)
#     for length in range(5,50, 5):
#         for transmit in range(length*2, length**2+1,length):
#             for prob in prob_pool:
#                 correct = 0
#                 start = time.time()
#                 for i in range(1000):
#                     correctString, generatedDataset = createDataset(length,transmit,prob)
#                     calculatedString = bma(np.array(generatedDataset))

#                     if(str(correctString) == str(calculatedString)):
#                         correct += 1
#                 per = (1000 - correct)*0.1
#                 end = time.time()
#                 tt = end - start

#                 temp = [length, transmit, prob, per,tt]
#                 csvwriter.writerow(temp)
#                 print(temp)

In [8]:
prob_pool = [0.01, 0.03, 0.1, 0.3, 1.0, 3.0, 10.0, 30.0]

header = ['Length', 'No. of Transmits', 'Deletion Probability', 'Percentage Error', 'Time Taken']

file = 'BMA Results 2.csv'

with open(file, 'w',newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(header)
    for length in range(10,100, 5):
        for transmit in range(1, length+1,math.isqrt(length)):
            for prob in prob_pool:
                correct = 0
                start = time.time()
                for i in range(1000):
                    correctString, generatedDataset = createDataset(length,transmit,prob)
                    calculatedString = bma(np.array(generatedDataset))

                    if(str(correctString) == str(calculatedString)):
                        correct += 1
                per = (1000 - correct)*0.1
                end = time.time()
                tt = end - start

                temp = [length, transmit, prob, per,tt]
                csvwriter.writerow(temp)
                print(temp)

[10, 1, 0.01, 0.1, 0.19646239280700684]
[10, 1, 0.03, 0.1, 0.17256951332092285]
[10, 1, 0.1, 1.4000000000000001, 0.17739272117614746]
[10, 1, 0.3, 2.0, 0.1735689640045166]
[10, 1, 1.0, 8.6, 0.1685481071472168]
[10, 1, 3.0, 24.900000000000002, 0.17253923416137695]
[10, 1, 10.0, 60.2, 0.1765275001525879]
[10, 1, 30.0, 96.10000000000001, 0.16755104064941406]
[10, 4, 0.01, 0.0, 0.24730610847473145]
[10, 4, 0.03, 0.0, 0.23939156532287598]
[10, 4, 0.1, 0.0, 0.24255967140197754]
[10, 4, 0.3, 0.0, 0.2453751564025879]
[10, 4, 1.0, 0.8, 0.2483046054840088]
[10, 4, 3.0, 6.5, 0.2563149929046631]
[10, 4, 10.0, 41.0, 0.25046873092651367]
[10, 4, 30.0, 96.4, 0.24134564399719238]
[10, 7, 0.01, 0.0, 0.3211476802825928]
[10, 7, 0.03, 0.0, 0.32931017875671387]
[10, 7, 0.1, 0.0, 0.3241572380065918]
[10, 7, 0.3, 0.0, 0.36500048637390137]
[10, 7, 1.0, 0.0, 0.3183097839355469]
[10, 7, 3.0, 0.6000000000000001, 0.3171820640563965]
[10, 7, 10.0, 18.6, 0.31116795539855957]
[10, 7, 30.0, 92.0, 0.30574560165405273

[35, 1, 0.01, 0.2, 0.3977084159851074]
[35, 1, 0.03, 1.0, 0.3942446708679199]
[35, 1, 0.1, 3.5, 0.39874792098999023]
[35, 1, 0.3, 9.5, 0.39629220962524414]
[35, 1, 1.0, 29.1, 0.41165757179260254]
[35, 1, 3.0, 62.7, 0.4180150032043457]
[35, 1, 10.0, 97.7, 0.41361355781555176]
[35, 1, 30.0, 100.0, 0.4854414463043213]
[35, 6, 0.01, 0.0, 0.9486589431762695]
[35, 6, 0.03, 0.0, 0.9681496620178223]
[35, 6, 0.1, 0.0, 0.830345630645752]
[35, 6, 0.3, 0.0, 0.833611249923706]
[35, 6, 1.0, 0.1, 0.8071722984313965]
[35, 6, 3.0, 7.800000000000001, 0.813812255859375]
[35, 6, 10.0, 76.7, 1.1814825534820557]
[35, 6, 30.0, 100.0, 1.31620192527771]
[35, 11, 0.01, 0.0, 2.031714677810669]
[35, 11, 0.03, 0.0, 2.0105931758880615]
[35, 11, 0.1, 0.0, 2.016834020614624]
[35, 11, 0.3, 0.0, 1.9726698398590088]
[35, 11, 1.0, 0.1, 2.0141468048095703]
[35, 11, 3.0, 1.2000000000000002, 1.9801414012908936]
[35, 11, 10.0, 52.6, 2.1226131916046143]
[35, 11, 30.0, 100.0, 1.911259651184082]
[35, 16, 0.01, 0.0, 2.2354035377

[50, 22, 0.1, 0.0, 3.3948779106140137]
[50, 22, 0.3, 0.0, 2.9786217212677]
[50, 22, 1.0, 0.0, 3.3616371154785156]
[50, 22, 3.0, 0.1, 3.380514144897461]
[50, 22, 10.0, 50.0, 2.868072748184204]
[50, 22, 30.0, 100.0, 3.3181214332580566]
[50, 29, 0.01, 0.0, 4.14889931678772]
[50, 29, 0.03, 0.0, 3.645998001098633]
[50, 29, 0.1, 0.0, 4.184535264968872]
[50, 29, 0.3, 0.0, 4.98093843460083]
[50, 29, 1.0, 0.0, 6.086393356323242]
[50, 29, 3.0, 0.0, 6.045527219772339]
[50, 29, 10.0, 44.0, 4.812096118927002]
[50, 29, 30.0, 100.0, 3.437073230743408]
[50, 36, 0.01, 0.0, 4.995394229888916]
[50, 36, 0.03, 0.0, 5.001168727874756]
[50, 36, 0.1, 0.0, 4.944267988204956]
[50, 36, 0.3, 0.0, 4.959205627441406]
[50, 36, 1.0, 0.0, 4.925504207611084]
[50, 36, 3.0, 0.0, 5.115682601928711]
[50, 36, 10.0, 39.7, 5.865221738815308]
[50, 36, 30.0, 100.0, 7.757050275802612]
[50, 43, 0.01, 0.0, 8.934548139572144]
[50, 43, 0.03, 0.0, 5.1531829833984375]
[50, 43, 0.1, 0.0, 5.772590160369873]
[50, 43, 0.3, 0.0, 5.72636342

[65, 25, 30.0, 100.0, 4.26707911491394]
[65, 33, 0.01, 0.0, 6.200858116149902]
[65, 33, 0.03, 0.0, 6.921924829483032]
[65, 33, 0.1, 0.0, 7.404027938842773]
[65, 33, 0.3, 0.0, 9.495595932006836]
[65, 33, 1.0, 0.0, 9.386006116867065]
[65, 33, 3.0, 0.0, 6.312680006027222]
[65, 33, 10.0, 51.900000000000006, 5.735276937484741]
[65, 33, 30.0, 100.0, 5.523493528366089]
[65, 41, 0.01, 0.0, 7.084650278091431]
[65, 41, 0.03, 0.0, 6.88770866394043]
[65, 41, 0.1, 0.0, 7.832719802856445]
[65, 41, 0.3, 0.0, 10.619831323623657]
[65, 41, 1.0, 0.0, 8.153717041015625]
[65, 41, 3.0, 0.0, 7.493002414703369]
[65, 41, 10.0, 49.0, 6.820055246353149]
[65, 41, 30.0, 100.0, 6.765260696411133]
[65, 49, 0.01, 0.0, 9.736283540725708]
[65, 49, 0.03, 0.0, 10.567501068115234]
[65, 49, 0.1, 0.0, 10.319039344787598]
[65, 49, 0.3, 0.0, 9.057895183563232]
[65, 49, 1.0, 0.0, 8.245624303817749]
[65, 49, 3.0, 0.1, 8.471839427947998]
[65, 49, 10.0, 44.900000000000006, 8.04330587387085]
[65, 49, 30.0, 100.0, 7.884381532669067

[80, 9, 0.03, 0.0, 4.551709890365601]
[80, 9, 0.1, 0.0, 4.610501050949097]
[80, 9, 0.3, 0.0, 4.508387088775635]
[80, 9, 1.0, 0.1, 4.520390748977661]
[80, 9, 3.0, 3.2, 4.043705940246582]
[80, 9, 10.0, 86.7, 4.119948148727417]
[80, 9, 30.0, 100.0, 3.4189977645874023]
[80, 17, 0.01, 0.0, 3.6572558879852295]
[80, 17, 0.03, 0.0, 4.1683807373046875]
[80, 17, 0.1, 0.0, 4.175142765045166]
[80, 17, 0.3, 0.0, 3.695772171020508]
[80, 17, 1.0, 0.0, 4.175210237503052]
[80, 17, 3.0, 0.6000000000000001, 4.169138669967651]
[80, 17, 10.0, 73.2, 3.5432753562927246]
[80, 17, 30.0, 100.0, 4.0665740966796875]
[80, 25, 0.01, 0.0, 5.5719122886657715]
[80, 25, 0.03, 0.0, 5.615488767623901]
[80, 25, 0.1, 0.0, 5.5638298988342285]
[80, 25, 0.3, 0.0, 8.101226091384888]
[80, 25, 1.0, 0.0, 8.506507158279419]
[80, 25, 3.0, 0.1, 6.094837427139282]
[80, 25, 10.0, 65.10000000000001, 5.908524513244629]
[80, 25, 30.0, 100.0, 6.54163670539856]
[80, 33, 0.01, 0.0, 11.54377555847168]
[80, 33, 0.03, 0.0, 11.787428379058838]


[90, 55, 1.0, 0.0, 13.067181587219238]
[90, 55, 3.0, 0.1, 20.331949949264526]
[90, 55, 10.0, 57.0, 18.26765012741089]
[90, 55, 30.0, 100.0, 11.86198616027832]
[90, 64, 0.01, 0.0, 15.938327550888062]
[90, 64, 0.03, 0.0, 20.786771535873413]
[90, 64, 0.1, 0.0, 23.370530128479004]
[90, 64, 0.3, 0.0, 27.325478315353394]
[90, 64, 1.0, 0.0, 29.468355894088745]
[90, 64, 3.0, 0.0, 19.176573038101196]
[90, 64, 10.0, 56.1, 26.56606936454773]
[90, 64, 30.0, 100.0, 27.645848035812378]
[90, 73, 0.01, 0.0, 30.077507972717285]
[90, 73, 0.03, 0.0, 23.01287841796875]
[90, 73, 0.1, 0.0, 16.590840101242065]
[90, 73, 0.3, 0.0, 16.645949840545654]
[90, 73, 1.0, 0.0, 23.343916416168213]
[90, 73, 3.0, 0.0, 19.875308990478516]
[90, 73, 10.0, 55.6, 21.271445989608765]
[90, 73, 30.0, 100.0, 15.823634624481201]
[90, 82, 0.01, 0.0, 18.884378671646118]
[90, 82, 0.03, 0.0, 18.439974308013916]
[90, 82, 0.1, 0.0, 18.981430292129517]
[90, 82, 0.3, 0.0, 26.479901790618896]
[90, 82, 1.0, 0.0, 28.427991151809692]
[90, 82,