# Bitwise Majority Alignment

# Main BMA Algorithm

In [1]:
import numpy as np
import random
import csv
import time
import math

In [2]:
def bmaByCode(receivedStringArray):
    noOfStrings, length = receivedStringArray.shape
    
    c = np.zeros(noOfStrings,dtype=int)
    transmittedString = np.zeros(length,dtype=int)
    
    for i in range(length):
        temp = [0,0]
        for j in range(noOfStrings):
            tmp = receivedStringArray[j,c[j]]
            temp[tmp] += 1
        index_max = np.argmax(temp)
        transmittedString[i] = index_max  
        
        for j in range(noOfStrings):
            temp = c[j]
            for k in range(temp+1,length):
                if(receivedStringArray[j,k] == index_max):
                    c[j] = k
                    break
                c[j] = length-1
            
                  

    return transmittedString

In [3]:
def bma(receivedStringArray):
    noOfStrings, length = receivedStringArray.shape
    
    c = np.zeros(noOfStrings,dtype=int)
    transmittedString = np.zeros(length,dtype=int)
    
    for i in range(length):
        temp = [0,0]
        for j in range(noOfStrings):
            tmp = receivedStringArray[j,c[j]]
            temp[tmp] += 1
        index_max = np.argmax(temp)
        transmittedString[i] = index_max  
        
        for j in range(noOfStrings):
            if receivedStringArray[j,c[j]] == transmittedString[i]:
                c[j] += 1
            else:
                continue
            
                  

    return transmittedString

In [4]:
#For Testing

print(bma(np.array([[1,1,1,1],[1,1,1,0],[1,1,1,1]])))

[1 1 1 1]


# Dataset Generation

In [5]:
def createDataset(length, noOfTransmissions, prob):
    transmittedString = np.zeros(length,dtype=int)
    matrix = np.zeros((noOfTransmissions,length),dtype=int)
    
    for i in range(length):
        transmittedString[i] = random.randint(0,1)
    
    for k in range(noOfTransmissions):
        temp = np.zeros(length,dtype=int)
        j = 0
        for i in range(length):
            a = random.choices([0,1], weights=(prob,100-prob), k=1)
            if(a == [0]):
                continue
            else:
                temp[j] = transmittedString[i]
                j += 1
        matrix[k] = temp
    
    return transmittedString, matrix

In [6]:
correctString, generatedDataset = createDataset(5,10,10)
calculatedString = bma(np.array(generatedDataset))
   
print('Original String: {}\nGenerated Matrix:\n {}\nCalculated String: {}'.format(correctString,  generatedDataset, calculatedString))

Original String: [1 0 1 0 1]
Generated Matrix:
 [[1 0 1 0 1]
 [1 0 1 0 1]
 [1 1 0 1 0]
 [1 0 1 1 0]
 [1 0 0 0 0]
 [1 1 0 1 0]
 [1 1 0 1 0]
 [1 0 1 1 0]
 [1 0 1 0 1]
 [1 0 1 0 1]]
Calculated String: [1 0 1 0 1]


# Validation of the Algorithm

In [7]:
# prob_pool = [0.01, 0.03, 0.1, 0.3, 1.0, 3.0, 10.0, 30.0]

# header = ['Length', 'No. of Transmits', 'Deletion Probability', 'Percentage Error', 'Time Taken']

# file = 'BMA Results.csv'

# with open(file, 'w',newline='') as csvfile:
#     csvwriter = csv.writer(csvfile)
#     csvwriter.writerow(header)
#     for length in range(10,100, 5):
#         for transmit in range(1, length+1,math.isqrt(length)):
#             for prob in prob_pool:
#                 correct = 0
#                 start = time.time()
#                 for i in range(1000):
#                     correctString, generatedDataset = createDataset(length,transmit,prob)
#                     calculatedString = bma(np.array(generatedDataset))

#                     if(str(correctString) == str(calculatedString)):
#                         correct += 1
#                 per = (1000 - correct)*0.1
#                 end = time.time()
#                 tt = end - start

#                 temp = [length, transmit, prob, per,tt]
#                 csvwriter.writerow(temp)

We now take more realistic values of the original DNA reconstruction problem. For that, the limits are as follows:

 - Probabilities: 0.1% to 10% in multiples of 3
 - Length of original string: 10-100 in steps of 2
 - No of transmits: 3-50 in steps of 2

In [ ]:
prob_pool = [0.1, 0.3, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 10.0]

header = ['Length', 'No. of Transmits', 'Deletion Probability', 'Percentage Error', 'Time Taken']

file = 'BMA Results(Realistic).csv'

with open(file, 'w',newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(header)
    for length in range(10,101, 2):
        for transmit in range(3, 52, 2):
            for prob in prob_pool:
                correct = 0
                tt = 0
                for i in range(1000):
                    correctString, generatedDataset = createDataset(length,transmit,prob)
                    start = time.time()
                    calculatedString = bma(np.array(generatedDataset))
     
                    if(str(correctString) == str(calculatedString)):
                        correct += 1
                    end = time.time()
                    tt += (end-start)
                per = (1000 - correct)*0.1

                temp = [length, transmit, prob, per,tt]
                print(temp)
                csvwriter.writerow(temp)

[10, 3, 0.1, 0.0, 0.16637563705444336]
[10, 3, 0.3, 0.0, 0.15494036674499512]
[10, 3, 1.0, 0.4, 0.17731142044067383]
[10, 3, 1.5, 1.4000000000000001, 0.15338730812072754]
[10, 3, 2.0, 2.4000000000000004, 0.16613507270812988]
[10, 3, 2.5, 3.5, 0.1547255516052246]
[10, 3, 3.0, 6.7, 0.16199469566345215]
[10, 3, 3.5, 6.5, 0.15376853942871094]
[10, 3, 4.0, 9.8, 0.1602339744567871]
[10, 3, 4.5, 11.200000000000001, 0.16484761238098145]
[10, 3, 5.0, 12.8, 0.15604472160339355]
[10, 3, 10.0, 39.400000000000006, 0.16559743881225586]
[10, 5, 0.1, 0.0, 0.1921219825744629]
[10, 5, 0.3, 0.0, 0.16493892669677734]
[10, 5, 1.0, 0.0, 0.17941069602966309]
[10, 5, 1.5, 0.2, 0.17406773567199707]
[10, 5, 2.0, 0.7000000000000001, 0.1592869758605957]
[10, 5, 2.5, 0.8, 0.1761481761932373]
[10, 5, 3.0, 1.8, 0.17887020111083984]
[10, 5, 3.5, 1.4000000000000001, 0.16593170166015625]
[10, 5, 4.0, 3.4000000000000004, 0.17584013938903809]
[10, 5, 4.5, 4.1000000000000005, 0.18667888641357422]
[10, 5, 5.0, 7.0, 0.17125

[10, 35, 3.5, 0.0, 0.57082200050354]
[10, 35, 4.0, 0.0, 0.3029608726501465]
[10, 35, 4.5, 0.0, 0.4311063289642334]
[10, 35, 5.0, 0.0, 0.4355010986328125]
[10, 35, 10.0, 5.800000000000001, 0.4563777446746826]
[10, 37, 0.1, 0.0, 0.5696101188659668]
[10, 37, 0.3, 0.0, 0.40970492362976074]
[10, 37, 1.0, 0.0, 0.4110395908355713]
[10, 37, 1.5, 0.0, 0.4941086769104004]
[10, 37, 2.0, 0.0, 0.5010926723480225]
[10, 37, 2.5, 0.0, 0.451082706451416]
[10, 37, 3.0, 0.0, 0.47060489654541016]
[10, 37, 3.5, 0.0, 0.44200968742370605]
[10, 37, 4.0, 0.0, 0.4634439945220947]
[10, 37, 4.5, 0.0, 0.46401381492614746]
[10, 37, 5.0, 0.0, 0.46136474609375]
[10, 37, 10.0, 4.7, 0.4595527648925781]
[10, 39, 0.1, 0.0, 0.49598169326782227]
[10, 39, 0.3, 0.0, 0.5543792247772217]
[10, 39, 1.0, 0.0, 0.5697817802429199]
[10, 39, 1.5, 0.0, 0.6236960887908936]
[10, 39, 2.0, 0.0, 0.5837194919586182]
[10, 39, 2.5, 0.0, 0.5761761665344238]
[10, 39, 3.0, 0.0, 0.5601222515106201]
[10, 39, 3.5, 0.0, 0.6172332763671875]
[10, 39, 

[12, 19, 2.0, 0.0, 0.4589989185333252]
[12, 19, 2.5, 0.0, 0.32515621185302734]
[12, 19, 3.0, 0.0, 0.349959135055542]
[12, 19, 3.5, 0.0, 0.3419301509857178]
[12, 19, 4.0, 0.0, 0.32256436347961426]
[12, 19, 4.5, 0.30000000000000004, 0.3297536373138428]
[12, 19, 5.0, 0.4, 0.5403769016265869]
[12, 19, 10.0, 10.5, 0.3712022304534912]
[12, 21, 0.1, 0.0, 0.34354209899902344]
[12, 21, 0.3, 0.0, 0.34847378730773926]
[12, 21, 1.0, 0.0, 0.3344392776489258]
[12, 21, 1.5, 0.0, 0.3477504253387451]
[12, 21, 2.0, 0.0, 0.5009825229644775]
[12, 21, 2.5, 0.1, 0.45674991607666016]
[12, 21, 3.0, 0.1, 0.3431069850921631]
[12, 21, 3.5, 0.0, 0.3484663963317871]
[12, 21, 4.0, 0.1, 0.35436463356018066]
[12, 21, 4.5, 0.0, 0.34137868881225586]
[12, 21, 5.0, 0.5, 0.46015143394470215]
[12, 21, 10.0, 11.4, 0.5744314193725586]
[12, 23, 0.1, 0.0, 0.6219766139984131]
[12, 23, 0.3, 0.0, 0.5861010551452637]
[12, 23, 1.0, 0.0, 0.6480143070220947]
[12, 23, 1.5, 0.0, 0.6140697002410889]
[12, 23, 2.0, 0.0, 0.6070220470428467

[14, 3, 3.5, 10.3, 0.20674729347229004]
[14, 3, 4.0, 12.0, 0.2071824073791504]
[14, 3, 4.5, 14.8, 0.18546271324157715]
[14, 3, 5.0, 17.2, 0.20289897918701172]
[14, 3, 10.0, 47.0, 0.1994643211364746]
[14, 5, 0.1, 0.0, 0.27774524688720703]
[14, 5, 0.3, 0.0, 0.26068758964538574]
[14, 5, 1.0, 0.2, 0.22162866592407227]
[14, 5, 1.5, 0.4, 0.21943926811218262]
[14, 5, 2.0, 0.9, 0.2501816749572754]
[14, 5, 2.5, 1.9000000000000001, 0.37302398681640625]
[14, 5, 3.0, 2.1, 0.40493202209472656]
[14, 5, 3.5, 4.2, 0.2698636054992676]
[14, 5, 4.0, 5.5, 0.23657608032226562]
[14, 5, 4.5, 8.200000000000001, 0.21894121170043945]
[14, 5, 5.0, 8.5, 0.2444596290588379]
[14, 5, 10.0, 34.800000000000004, 0.25121235847473145]
[14, 7, 0.1, 0.0, 0.2508707046508789]
[14, 7, 0.3, 0.0, 0.2702639102935791]
[14, 7, 1.0, 0.0, 0.24845600128173828]
[14, 7, 1.5, 0.30000000000000004, 0.23258614540100098]
[14, 7, 2.0, 0.1, 0.26410508155822754]
[14, 7, 2.5, 0.9, 0.40073132514953613]
[14, 7, 3.0, 0.5, 0.35988736152648926]
[14,

[14, 37, 3.0, 0.0, 0.9613573551177979]
[14, 37, 3.5, 0.0, 0.9887657165527344]
[14, 37, 4.0, 0.0, 0.9972376823425293]
[14, 37, 4.5, 0.2, 1.058197259902954]
[14, 37, 5.0, 0.30000000000000004, 1.0150926113128662]
[14, 37, 10.0, 9.1, 0.9722771644592285]
[14, 39, 0.1, 0.0, 1.0341496467590332]
[14, 39, 0.3, 0.0, 0.9977366924285889]
[14, 39, 1.0, 0.0, 0.6137027740478516]
[14, 39, 1.5, 0.0, 0.6017951965332031]
[14, 39, 2.0, 0.0, 0.7895774841308594]
[14, 39, 2.5, 0.0, 0.6438541412353516]
[14, 39, 3.0, 0.0, 0.6009254455566406]
[14, 39, 3.5, 0.0, 0.6394827365875244]
[14, 39, 4.0, 0.0, 0.7392385005950928]
[14, 39, 4.5, 0.0, 0.5774476528167725]
[14, 39, 5.0, 0.1, 0.5917346477508545]
[14, 39, 10.0, 10.3, 0.7763686180114746]
[14, 41, 0.1, 0.0, 0.6036393642425537]
[14, 41, 0.3, 0.0, 0.6008572578430176]
[14, 41, 1.0, 0.0, 0.8108067512512207]
[14, 41, 1.5, 0.0, 0.5974631309509277]
[14, 41, 2.0, 0.0, 0.5862114429473877]
[14, 41, 2.5, 0.0, 0.768282413482666]
[14, 41, 3.0, 0.0, 0.6336641311645508]
[14, 41,

[16, 21, 1.5, 0.0, 0.7247657775878906]
[16, 21, 2.0, 0.0, 0.7243516445159912]
[16, 21, 2.5, 0.0, 0.7520468235015869]
[16, 21, 3.0, 0.0, 0.6550734043121338]
[16, 21, 3.5, 0.0, 0.46559929847717285]
[16, 21, 4.0, 0.2, 0.41544580459594727]
[16, 21, 4.5, 0.6000000000000001, 0.46219849586486816]
[16, 21, 5.0, 0.7000000000000001, 0.51177978515625]
[16, 21, 10.0, 16.8, 0.5858747959136963]
[16, 23, 0.1, 0.0, 0.5034945011138916]
[16, 23, 0.3, 0.0, 0.4138307571411133]
[16, 23, 1.0, 0.0, 0.4423868656158447]
[16, 23, 1.5, 0.0, 0.5057604312896729]
[16, 23, 2.0, 0.0, 0.622215986251831]
[16, 23, 2.5, 0.0, 0.61918044090271]
[16, 23, 3.0, 0.2, 0.4487893581390381]
[16, 23, 3.5, 0.1, 0.4987773895263672]
[16, 23, 4.0, 0.1, 0.46818113327026367]
[16, 23, 4.5, 0.30000000000000004, 0.7163050174713135]
[16, 23, 5.0, 0.6000000000000001, 0.5192668437957764]
[16, 23, 10.0, 14.0, 0.43457531929016113]
[16, 25, 0.1, 0.0, 0.5014426708221436]
[16, 25, 0.3, 0.0, 0.6185963153839111]
[16, 25, 1.0, 0.0, 0.5959475040435791]

[18, 5, 2.0, 0.9, 0.4236013889312744]
[18, 5, 2.5, 2.5, 0.46164512634277344]
[18, 5, 3.0, 5.2, 0.41265010833740234]
[18, 5, 3.5, 6.5, 0.4397449493408203]
[18, 5, 4.0, 8.200000000000001, 0.428485631942749]
[18, 5, 4.5, 8.4, 0.4346160888671875]
[18, 5, 5.0, 10.4, 0.4606013298034668]
[18, 5, 10.0, 45.1, 0.436126708984375]
[18, 7, 0.1, 0.0, 0.5031149387359619]
[18, 7, 0.3, 0.0, 0.47287869453430176]
[18, 7, 1.0, 0.2, 0.3287832736968994]
[18, 7, 1.5, 0.1, 0.2789912223815918]
[18, 7, 2.0, 0.1, 0.3102877140045166]
[18, 7, 2.5, 1.0, 0.29770755767822266]
[18, 7, 3.0, 1.2000000000000002, 0.2896702289581299]
[18, 7, 3.5, 1.9000000000000001, 0.28577256202697754]
[18, 7, 4.0, 3.1, 0.2987785339355469]
[18, 7, 4.5, 3.9000000000000004, 0.2937173843383789]
[18, 7, 5.0, 6.2, 0.4966697692871094]
[18, 7, 10.0, 35.1, 0.4008157253265381]
[18, 9, 0.1, 0.0, 0.32873106002807617]
[18, 9, 0.3, 0.0, 0.3195340633392334]
[18, 9, 1.0, 0.0, 0.3176271915435791]
[18, 9, 1.5, 0.0, 0.32311415672302246]
[18, 9, 2.0, 0.3000

[18, 39, 1.0, 0.0, 1.4206135272979736]
[18, 39, 1.5, 0.0, 1.298311710357666]
[18, 39, 2.0, 0.0, 1.3356914520263672]
[18, 39, 2.5, 0.0, 1.458404779434204]
[18, 39, 3.0, 0.0, 1.4338784217834473]
[18, 39, 3.5, 0.0, 1.3137142658233643]
[18, 39, 4.0, 0.0, 0.9235453605651855]
[18, 39, 4.5, 0.0, 0.7543776035308838]
[18, 39, 5.0, 0.2, 1.0098845958709717]
[18, 39, 10.0, 12.200000000000001, 0.7784132957458496]
[18, 41, 0.1, 0.0, 0.9069621562957764]
[18, 41, 0.3, 0.0, 0.8362140655517578]
[18, 41, 1.0, 0.0, 0.7763614654541016]
[18, 41, 1.5, 0.0, 0.9789857864379883]
[18, 41, 2.0, 0.0, 0.7474472522735596]
[18, 41, 2.5, 0.0, 0.9254415035247803]
[18, 41, 3.0, 0.0, 0.8237972259521484]
[18, 41, 3.5, 0.0, 0.8441987037658691]
[18, 41, 4.0, 0.0, 0.953113317489624]
[18, 41, 4.5, 0.2, 0.7786130905151367]
[18, 41, 5.0, 0.2, 0.9110350608825684]
[18, 41, 10.0, 13.200000000000001, 0.8106539249420166]
[18, 43, 0.1, 0.0, 0.7765040397644043]
[18, 43, 0.3, 0.0, 1.018291711807251]
[18, 43, 1.0, 0.0, 0.778608322143554