# Bitwise Majority Alignment

# Main BMA Algorithm

In [1]:
import numpy as np
import random
import csv
import time
import math

In [2]:
def bmaByCode(receivedStringArray):
    noOfStrings, length = receivedStringArray.shape
    
    c = np.zeros(noOfStrings,dtype=int)
    transmittedString = np.zeros(length,dtype=int)
    
    for i in range(length):
        temp = [0,0]
        for j in range(noOfStrings):
            tmp = receivedStringArray[j,c[j]]
            temp[tmp] += 1
        index_max = np.argmax(temp)
        transmittedString[i] = index_max  
        
        for j in range(noOfStrings):
            temp = c[j]
            for k in range(temp+1,length):
                if(receivedStringArray[j,k] == index_max):
                    c[j] = k
                    break
                c[j] = length-1
            
                  

    return transmittedString

In [3]:
def bma(receivedStringArray):
    noOfStrings, length = receivedStringArray.shape
    
    c = np.zeros(noOfStrings,dtype=int)
    transmittedString = np.zeros(length,dtype=int)
    
    for i in range(length):
        temp = [0,0]
        for j in range(noOfStrings):
            tmp = receivedStringArray[j,c[j]]
            temp[tmp] += 1
        index_max = np.argmax(temp)
        transmittedString[i] = index_max  
        
        for j in range(noOfStrings):
            if receivedStringArray[j,c[j]] == transmittedString[i]:
                c[j] += 1
            else:
                continue
            
                  

    return transmittedString

In [4]:
#For Testing

print(bma(np.array([[1,1,1,1],[1,1,1,0],[1,1,1,1]])))

[1 1 1 1]


# Dataset Generation

In [5]:
def createDataset(length, noOfTransmissions, prob):
    transmittedString = np.zeros(length,dtype=int)
    matrix = np.zeros((noOfTransmissions,length),dtype=int)
    
    for i in range(length):
        transmittedString[i] = random.randint(0,1)
    
    for k in range(noOfTransmissions):
        temp = np.zeros(length,dtype=int)
        j = 0
        for i in range(length):
            a = random.choices([0,1], weights=(prob,100-prob), k=1)
            if(a == [0]):
                continue
            else:
                temp[j] = transmittedString[i]
                j += 1
        matrix[k] = temp
    
    return transmittedString, matrix

In [6]:
correctString, generatedDataset = createDataset(5,10,10)
calculatedString = bma(np.array(generatedDataset))
   
print('Original String: {}\nGenerated Matrix:\n {}\nCalculated String: {}'.format(correctString,  generatedDataset, calculatedString))

Original String: [0 0 1 0 1]
Generated Matrix:
 [[0 0 1 0 1]
 [0 0 1 0 1]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [0 0 1 0 1]
 [0 0 1 0 1]
 [0 0 1 0 1]
 [0 0 1 0 1]
 [0 0 1 0 1]
 [0 0 1 0 1]]
Calculated String: [0 0 1 0 1]


# Validation of the Algorithm

In [7]:
# prob_pool = [0.01, 0.03, 0.1, 0.3, 1.0, 3.0, 10.0, 30.0]

# header = ['Length', 'No. of Transmits', 'Deletion Probability', 'Percentage Error', 'Time Taken']

# file = 'BMA Results.csv'

# with open(file, 'w',newline='') as csvfile:
#     csvwriter = csv.writer(csvfile)
#     csvwriter.writerow(header)
#     for length in range(10,100, 5):
#         for transmit in range(1, length+1,math.isqrt(length)):
#             for prob in prob_pool:
#                 correct = 0
#                 start = time.time()
#                 for i in range(1000):
#                     correctString, generatedDataset = createDataset(length,transmit,prob)
#                     calculatedString = bma(np.array(generatedDataset))

#                     if(str(correctString) == str(calculatedString)):
#                         correct += 1
#                 per = (1000 - correct)*0.1
#                 end = time.time()
#                 tt = end - start

#                 temp = [length, transmit, prob, per,tt]
#                 csvwriter.writerow(temp)

We now take more realistic values of the original DNA reconstruction problem. For that, the limits are as follows:

 - Probabilities: 0.1% to 10% in multiples of 3
 - Length of original string: 10-100 in steps of 2
 - No of transmits: 3-50 in steps of 2

In [8]:
prob_pool = [0.1, 0.3, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 10.0]

header = ['Length', 'No. of Transmits', 'Deletion Probability', 'Percentage Error', 'Time Taken']

file = 'BMA Results(Realistic).csv'

with open(file, 'w',newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(header)
    for length in range(10,101, 5):
        for transmit in range(3, 52, 3):
            for prob in prob_pool:
                correct = 0
                tt = 0
                for i in range(1000):
                    correctString, generatedDataset = createDataset(length,transmit,prob)
                    start = time.time()
                    calculatedString = bma(np.array(generatedDataset))
     
                    if(str(correctString) == str(calculatedString)):
                        correct += 1
                    end = time.time()
                    tt += (end-start)
                per = (1000 - correct)*0.1

                temp = [length, transmit, prob, per,tt]
                print(temp)
                csvwriter.writerow(temp)

[10, 3, 0.1, 0.0, 0.14778733253479004]
[10, 3, 0.3, 0.0, 0.157548189163208]
[10, 3, 1.0, 0.7000000000000001, 0.15257620811462402]
[10, 3, 1.5, 1.3, 0.14155030250549316]
[10, 3, 2.0, 1.2000000000000002, 0.17452454566955566]
[10, 3, 2.5, 3.6, 0.1685776710510254]
[10, 3, 3.0, 5.9, 0.15155696868896484]
[10, 3, 3.5, 6.4, 0.1574540138244629]
[10, 3, 4.0, 9.600000000000001, 0.144697904586792]
[10, 3, 4.5, 11.200000000000001, 0.18741822242736816]
[10, 3, 5.0, 11.9, 0.13357901573181152]
[10, 3, 10.0, 36.4, 0.17563915252685547]
[10, 6, 0.1, 0.0, 0.20018482208251953]
[10, 6, 0.3, 0.0, 0.1816082000732422]
[10, 6, 1.0, 0.0, 0.17544794082641602]
[10, 6, 1.5, 0.0, 0.20747900009155273]
[10, 6, 2.0, 1.0, 0.1893761157989502]
[10, 6, 2.5, 1.3, 0.20540642738342285]
[10, 6, 3.0, 1.9000000000000001, 0.2063617706298828]
[10, 6, 3.5, 3.0, 0.1743783950805664]
[10, 6, 4.0, 4.1000000000000005, 0.28315258026123047]
[10, 6, 4.5, 3.9000000000000004, 0.3121681213378906]
[10, 6, 5.0, 6.800000000000001, 0.290095567703

[10, 51, 5.0, 0.0, 0.5714783668518066]
[10, 51, 10.0, 4.9, 0.6481304168701172]
[15, 3, 0.1, 0.0, 0.2145087718963623]
[15, 3, 0.3, 0.2, 0.20444297790527344]
[15, 3, 1.0, 1.6, 0.20346808433532715]
[15, 3, 1.5, 1.2000000000000002, 0.2023940086364746]
[15, 3, 2.0, 3.6, 0.21443700790405273]
[15, 3, 2.5, 5.1000000000000005, 0.1965043544769287]
[15, 3, 3.0, 8.6, 0.20943951606750488]
[15, 3, 3.5, 10.3, 0.21143174171447754]
[15, 3, 4.0, 13.8, 0.2164905071258545]
[15, 3, 4.5, 15.700000000000001, 0.199418306350708]
[15, 3, 5.0, 19.0, 0.3341045379638672]
[15, 3, 10.0, 55.800000000000004, 0.34928321838378906]
[15, 6, 0.1, 0.0, 0.34797239303588867]
[15, 6, 0.3, 0.0, 0.2383558750152588]
[15, 6, 1.0, 0.2, 0.22927474975585938]
[15, 6, 1.5, 0.30000000000000004, 0.23323965072631836]
[15, 6, 2.0, 1.4000000000000001, 0.23217010498046875]
[15, 6, 2.5, 2.1, 0.2324082851409912]
[15, 6, 3.0, 4.0, 0.2343285083770752]
[15, 6, 3.5, 3.8000000000000003, 0.2582676410675049]
[15, 6, 4.0, 6.800000000000001, 0.24120950

[15, 51, 3.0, 0.0, 1.1489372253417969]
[15, 51, 3.5, 0.0, 1.30283784866333]
[15, 51, 4.0, 0.0, 1.1510934829711914]
[15, 51, 4.5, 0.0, 1.2101521492004395]
[15, 51, 5.0, 0.4, 1.2866857051849365]
[15, 51, 10.0, 10.100000000000001, 1.2265210151672363]
[20, 3, 0.1, 0.0, 0.4505789279937744]
[20, 3, 0.3, 0.0, 0.3869915008544922]
[20, 3, 1.0, 1.2000000000000002, 0.3867912292480469]
[20, 3, 1.5, 2.9000000000000004, 0.4078338146209717]
[20, 3, 2.0, 6.0, 0.40586209297180176]
[20, 3, 2.5, 8.4, 0.4119749069213867]
[20, 3, 3.0, 11.5, 0.42696666717529297]
[20, 3, 3.5, 13.700000000000001, 0.45282697677612305]
[20, 3, 4.0, 19.3, 0.41599535942077637]
[20, 3, 4.5, 23.3, 0.457611083984375]
[20, 3, 5.0, 27.700000000000003, 0.4087562561035156]
[20, 3, 10.0, 62.1, 0.4397728443145752]
[20, 6, 0.1, 0.0, 0.35009169578552246]
[20, 6, 0.3, 0.0, 0.3320939540863037]
[20, 6, 1.0, 0.1, 0.35402727127075195]
[20, 6, 1.5, 0.5, 0.28821802139282227]
[20, 6, 2.0, 1.9000000000000001, 0.28622889518737793]
[20, 6, 2.5, 2.8000

[20, 51, 1.0, 0.0, 1.5306847095489502]
[20, 51, 1.5, 0.0, 1.6066699028015137]
[20, 51, 2.0, 0.0, 1.50614333152771]
[20, 51, 2.5, 0.0, 1.168715476989746]
[20, 51, 3.0, 0.0, 0.9208581447601318]
[20, 51, 3.5, 0.0, 1.1362228393554688]
[20, 51, 4.0, 0.1, 1.1015186309814453]
[20, 51, 4.5, 0.0, 0.954880952835083]
[20, 51, 5.0, 0.1, 0.962914228439331]
[20, 51, 10.0, 14.3, 1.1067323684692383]
[25, 3, 0.1, 0.0, 0.30115342140197754]
[25, 3, 0.3, 0.2, 0.3162052631378174]
[25, 3, 1.0, 1.6, 0.2952265739440918]
[25, 3, 1.5, 5.5, 0.298353910446167]
[25, 3, 2.0, 8.700000000000001, 0.3082163333892822]
[25, 3, 2.5, 10.0, 0.3034825325012207]
[25, 3, 3.0, 16.5, 0.3421778678894043]
[25, 3, 3.5, 19.8, 0.4587523937225342]
[25, 3, 4.0, 20.6, 0.5036804676055908]
[25, 3, 4.5, 28.900000000000002, 0.47173094749450684]
[25, 3, 5.0, 33.6, 0.4757258892059326]
[25, 3, 10.0, 73.10000000000001, 0.5235681533813477]
[25, 6, 0.1, 0.0, 0.5653624534606934]
[25, 6, 0.3, 0.0, 0.5566437244415283]
[25, 6, 1.0, 0.4, 0.60238575935

[25, 48, 5.0, 0.30000000000000004, 1.362328290939331]
[25, 48, 10.0, 17.400000000000002, 1.234783411026001]
[25, 51, 0.1, 0.0, 1.3884010314941406]
[25, 51, 0.3, 0.0, 1.5360970497131348]
[25, 51, 1.0, 0.0, 1.202791452407837]
[25, 51, 1.5, 0.0, 1.8173441886901855]
[25, 51, 2.0, 0.0, 1.8651719093322754]
[25, 51, 2.5, 0.0, 2.019569158554077]
[25, 51, 3.0, 0.0, 2.310854911804199]
[25, 51, 3.5, 0.0, 2.1903388500213623]
[25, 51, 4.0, 0.1, 1.9747271537780762]
[25, 51, 4.5, 0.0, 2.031264305114746]
[25, 51, 5.0, 0.0, 1.9219536781311035]
[25, 51, 10.0, 18.900000000000002, 2.0165374279022217]
[30, 3, 0.1, 0.0, 0.5655016899108887]
[30, 3, 0.3, 0.2, 0.5644221305847168]
[30, 3, 1.0, 2.6, 0.6312501430511475]
[30, 3, 1.5, 4.4, 0.5784766674041748]
[30, 3, 2.0, 7.7, 0.6404128074645996]
[30, 3, 2.5, 11.5, 0.6482737064361572]
[30, 3, 3.0, 17.8, 0.5505218505859375]
[30, 3, 3.5, 23.200000000000003, 0.6103324890136719]
[30, 3, 4.0, 28.1, 0.6280360221862793]
[30, 3, 4.5, 33.7, 0.5525076389312744]
[30, 3, 5.0, 

[30, 48, 2.5, 0.0, 2.462402105331421]
[30, 48, 3.0, 0.0, 2.142362117767334]
[30, 48, 3.5, 0.1, 2.142496347427368]
[30, 48, 4.0, 0.1, 2.1744282245635986]
[30, 48, 4.5, 0.1, 2.160700798034668]
[30, 48, 5.0, 0.2, 2.1672842502593994]
[30, 48, 10.0, 24.3, 2.218047618865967]
[30, 51, 0.1, 0.0, 2.2723922729492188]
[30, 51, 0.3, 0.0, 2.3457717895507812]
[30, 51, 1.0, 0.0, 2.179159164428711]
[30, 51, 1.5, 0.0, 2.255946397781372]
[30, 51, 2.0, 0.0, 2.2152698040008545]
[30, 51, 2.5, 0.0, 1.919008731842041]
[30, 51, 3.0, 0.0, 1.8269236087799072]
[30, 51, 3.5, 0.0, 1.5160207748413086]
[30, 51, 4.0, 0.1, 2.252164363861084]
[30, 51, 4.5, 0.2, 2.336627721786499]
[30, 51, 5.0, 0.5, 2.3536336421966553]
[30, 51, 10.0, 21.200000000000003, 2.1629886627197266]
[35, 3, 0.1, 0.0, 0.6822986602783203]
[35, 3, 0.3, 0.0, 0.6472482681274414]
[35, 3, 1.0, 2.8000000000000003, 0.6451466083526611]
[35, 3, 1.5, 5.9, 0.6602580547332764]
[35, 3, 2.0, 10.0, 0.5565147399902344]
[35, 3, 2.5, 15.4, 0.6153790950775146]
[35, 3

[35, 48, 1.5, 0.0, 2.399925470352173]
[35, 48, 2.0, 0.0, 2.3695068359375]
[35, 48, 2.5, 0.0, 2.4229087829589844]
[35, 48, 3.0, 0.0, 2.4098289012908936]
[35, 48, 3.5, 0.1, 2.469787120819092]
[35, 48, 4.0, 0.1, 2.5416698455810547]
[35, 48, 4.5, 0.5, 2.4304897785186768]
[35, 48, 5.0, 0.7000000000000001, 2.3279335498809814]
[35, 48, 10.0, 29.700000000000003, 2.355659246444702]
[35, 51, 0.1, 0.0, 2.5402841567993164]
[35, 51, 0.3, 0.0, 2.619018077850342]
[35, 51, 1.0, 0.0, 2.5789918899536133]
[35, 51, 1.5, 0.0, 2.635226011276245]
[35, 51, 2.0, 0.0, 2.6747994422912598]
[35, 51, 2.5, 0.0, 2.5956506729125977]
[35, 51, 3.0, 0.0, 2.602651596069336]
[35, 51, 3.5, 0.0, 2.5320000648498535]
[35, 51, 4.0, 0.1, 2.4835805892944336]
[35, 51, 4.5, 0.30000000000000004, 2.497161865234375]
[35, 51, 5.0, 0.5, 2.465725898742676]
[35, 51, 10.0, 27.900000000000002, 2.432534694671631]
[40, 3, 0.1, 0.0, 0.7190334796905518]
[40, 3, 0.3, 0.30000000000000004, 0.7229213714599609]
[40, 3, 1.0, 3.5, 0.7828390598297119]


[40, 45, 10.0, 30.0, 2.6458306312561035]
[40, 48, 0.1, 0.0, 2.873260021209717]
[40, 48, 0.3, 0.0, 2.813422203063965]
[40, 48, 1.0, 0.0, 2.967081308364868]
[40, 48, 1.5, 0.0, 2.783992052078247]
[40, 48, 2.0, 0.0, 2.8654041290283203]
[40, 48, 2.5, 0.0, 2.727710723876953]
[40, 48, 3.0, 0.1, 2.667963981628418]
[40, 48, 3.5, 0.0, 2.7227232456207275]
[40, 48, 4.0, 0.0, 2.748826026916504]
[40, 48, 4.5, 0.30000000000000004, 2.628751039505005]
[40, 48, 5.0, 1.0, 2.6699628829956055]
[40, 48, 10.0, 30.400000000000002, 2.689711093902588]
[40, 51, 0.1, 0.0, 2.819546699523926]
[40, 51, 0.3, 0.0, 2.9005286693573]
[40, 51, 1.0, 0.0, 2.9475927352905273]
[40, 51, 1.5, 0.0, 3.062889814376831]
[40, 51, 2.0, 0.0, 2.950927495956421]
[40, 51, 2.5, 0.0, 3.0816237926483154]
[40, 51, 3.0, 0.0, 2.99897837638855]
[40, 51, 3.5, 0.0, 2.9694173336029053]
[40, 51, 4.0, 0.1, 2.8162105083465576]
[40, 51, 4.5, 0.2, 2.795748472213745]
[40, 51, 5.0, 0.8, 2.9268810749053955]
[40, 51, 10.0, 28.3, 2.783827304840088]
[45, 3, 

[45, 45, 3.0, 0.0, 2.9391000270843506]
[45, 45, 3.5, 0.0, 2.866222858428955]
[45, 45, 4.0, 0.0, 2.902017593383789]
[45, 45, 4.5, 0.6000000000000001, 2.8367397785186768]
[45, 45, 5.0, 0.4, 1.9760820865631104]
[45, 45, 10.0, 33.1, 1.909865379333496]
[45, 48, 0.1, 0.0, 2.21733021736145]
[45, 48, 0.3, 0.0, 3.0501530170440674]
[45, 48, 1.0, 0.0, 3.0432422161102295]
[45, 48, 1.5, 0.0, 2.9922168254852295]
[45, 48, 2.0, 0.0, 3.0569353103637695]
[45, 48, 2.5, 0.0, 3.115006923675537]
[45, 48, 3.0, 0.0, 3.12475848197937]
[45, 48, 3.5, 0.1, 3.1346523761749268]
[45, 48, 4.0, 0.2, 3.0821776390075684]
[45, 48, 4.5, 0.30000000000000004, 3.1916897296905518]
[45, 48, 5.0, 1.4000000000000001, 3.0528507232666016]
[45, 48, 10.0, 34.6, 2.989504098892212]
[45, 51, 0.1, 0.0, 2.2913689613342285]
[45, 51, 0.3, 0.0, 2.3452811241149902]
[45, 51, 1.0, 0.0, 2.224072217941284]
[45, 51, 1.5, 0.0, 2.8741872310638428]
[45, 51, 2.0, 0.0, 3.155447483062744]
[45, 51, 2.5, 0.0, 3.126999616622925]
[45, 51, 3.0, 0.0, 3.12960

[50, 42, 10.0, 39.0, 3.9792513847351074]
[50, 45, 0.1, 0.0, 4.1353394985198975]
[50, 45, 0.3, 0.0, 4.737359523773193]
[50, 45, 1.0, 0.0, 4.694075345993042]
[50, 45, 1.5, 0.0, 3.9663212299346924]
[50, 45, 2.0, 0.0, 3.780705690383911]
[50, 45, 2.5, 0.0, 3.6683921813964844]
[50, 45, 3.0, 0.0, 3.77752423286438]
[50, 45, 3.5, 0.2, 3.68561053276062]
[50, 45, 4.0, 0.30000000000000004, 5.534884929656982]
[50, 45, 4.5, 0.7000000000000001, 4.938241958618164]
[50, 45, 5.0, 0.7000000000000001, 5.0074357986450195]
[50, 45, 10.0, 37.4, 5.784530878067017]
[50, 48, 0.1, 0.0, 5.110996961593628]
[50, 48, 0.3, 0.0, 4.622382640838623]
[50, 48, 1.0, 0.0, 4.29932713508606]
[50, 48, 1.5, 0.0, 4.2937891483306885]
[50, 48, 2.0, 0.0, 4.707122087478638]
[50, 48, 2.5, 0.0, 4.9681336879730225]
[50, 48, 3.0, 0.0, 5.861769199371338]
[50, 48, 3.5, 0.2, 6.067458391189575]
[50, 48, 4.0, 0.1, 5.430506944656372]
[50, 48, 4.5, 0.30000000000000004, 5.012990236282349]
[50, 48, 5.0, 1.6, 5.034201622009277]
[50, 48, 10.0, 37.

[55, 42, 5.0, 1.8, 4.990743637084961]
[55, 42, 10.0, 44.6, 5.085204601287842]
[55, 45, 0.1, 0.0, 5.387195825576782]
[55, 45, 0.3, 0.0, 4.5848822593688965]
[55, 45, 1.0, 0.0, 4.608624458312988]
[55, 45, 1.5, 0.0, 4.64258599281311]
[55, 45, 2.0, 0.0, 4.496983051300049]
[55, 45, 2.5, 0.0, 5.126532554626465]
[55, 45, 3.0, 0.0, 4.979423522949219]
[55, 45, 3.5, 0.1, 4.824082851409912]
[55, 45, 4.0, 0.2, 7.04004979133606]
[55, 45, 4.5, 0.0, 4.971760988235474]
[55, 45, 5.0, 0.8, 4.488016366958618]
[55, 45, 10.0, 42.300000000000004, 4.610928297042847]
[55, 48, 0.1, 0.0, 4.861987829208374]
[55, 48, 0.3, 0.0, 4.9243152141571045]
[55, 48, 1.0, 0.0, 5.6259520053863525]
[55, 48, 1.5, 0.0, 5.559079170227051]
[55, 48, 2.0, 0.0, 5.764614105224609]
[55, 48, 2.5, 0.0, 5.418294668197632]
[55, 48, 3.0, 0.0, 4.809666156768799]
[55, 48, 3.5, 0.0, 5.526445627212524]
[55, 48, 4.0, 0.2, 4.7524168491363525]
[55, 48, 4.5, 0.6000000000000001, 5.013023138046265]
[55, 48, 5.0, 0.9, 5.727444171905518]
[55, 48, 10.0, 

[60, 42, 2.0, 0.0, 3.894706964492798]
[60, 42, 2.5, 0.0, 3.814791202545166]
[60, 42, 3.0, 0.1, 3.7737691402435303]
[60, 42, 3.5, 0.0, 2.7666280269622803]
[60, 42, 4.0, 0.30000000000000004, 3.028444528579712]
[60, 42, 4.5, 0.7000000000000001, 3.825674533843994]
[60, 42, 5.0, 0.8, 3.71120023727417]
[60, 42, 10.0, 43.6, 3.816464424133301]
[60, 45, 0.1, 0.0, 4.073317289352417]
[60, 45, 0.3, 0.0, 4.038607835769653]
[60, 45, 1.0, 0.0, 3.985419988632202]
[60, 45, 1.5, 0.0, 3.056058645248413]
[60, 45, 2.0, 0.0, 2.8297646045684814]
[60, 45, 2.5, 0.0, 3.0717506408691406]
[60, 45, 3.0, 0.0, 3.343320369720459]
[60, 45, 3.5, 0.0, 4.607769012451172]
[60, 45, 4.0, 0.2, 3.888301372528076]
[60, 45, 4.5, 0.5, 3.861297845840454]
[60, 45, 5.0, 0.8, 3.850066661834717]
[60, 45, 10.0, 43.300000000000004, 3.762943744659424]
[60, 48, 0.1, 0.0, 4.033243417739868]
[60, 48, 0.3, 0.0, 2.861254930496216]
[60, 48, 1.0, 0.0, 2.979921817779541]
[60, 48, 1.5, 0.0, 4.025033473968506]
[60, 48, 2.0, 0.0, 4.377258777618408

[65, 42, 0.3, 0.0, 4.370283365249634]
[65, 42, 1.0, 0.0, 4.553015232086182]
[65, 42, 1.5, 0.0, 4.156867742538452]
[65, 42, 2.0, 0.0, 4.174310922622681]
[65, 42, 2.5, 0.0, 3.906442403793335]
[65, 42, 3.0, 0.1, 2.941429376602173]
[65, 42, 3.5, 0.0, 4.150660514831543]
[65, 42, 4.0, 0.30000000000000004, 4.21260929107666]
[65, 42, 4.5, 0.9, 4.207720994949341]
[65, 42, 5.0, 1.6, 4.352762699127197]
[65, 42, 10.0, 47.2, 4.6704466342926025]
[65, 45, 0.1, 0.0, 4.85842227935791]
[65, 45, 0.3, 0.0, 5.175321817398071]
[65, 45, 1.0, 0.0, 4.937130928039551]
[65, 45, 1.5, 0.0, 4.630814552307129]
[65, 45, 2.0, 0.0, 4.6258134841918945]
[65, 45, 2.5, 0.0, 3.5789530277252197]
[65, 45, 3.0, 0.0, 3.000192642211914]
[65, 45, 3.5, 0.0, 3.8176281452178955]
[65, 45, 4.0, 0.1, 4.477784156799316]
[65, 45, 4.5, 0.5, 5.0467588901519775]
[65, 45, 5.0, 0.9, 5.245806455612183]
[65, 45, 10.0, 47.900000000000006, 4.982213258743286]
[65, 48, 0.1, 0.0, 5.071086168289185]
[65, 48, 0.3, 0.0, 4.5350236892700195]
[65, 48, 1.0

[70, 39, 5.0, 1.7000000000000002, 4.623727798461914]
[70, 39, 10.0, 48.400000000000006, 4.7194836139678955]
[70, 42, 0.1, 0.0, 4.4226484298706055]
[70, 42, 0.3, 0.0, 4.58812141418457]
[70, 42, 1.0, 0.0, 3.4627413749694824]
[70, 42, 1.5, 0.0, 3.1525208950042725]
[70, 42, 2.0, 0.0, 4.366250276565552]
[70, 42, 2.5, 0.0, 4.425961256027222]
[70, 42, 3.0, 0.1, 4.841685771942139]
[70, 42, 3.5, 0.0, 5.07350492477417]
[70, 42, 4.0, 0.2, 8.95531702041626]
[70, 42, 4.5, 0.8, 3.1216728687286377]
[70, 42, 5.0, 1.5, 3.2027134895324707]
[70, 42, 10.0, 50.2, 3.1515839099884033]
[70, 45, 0.1, 0.0, 3.579486608505249]
[70, 45, 0.3, 0.0, 3.276090621948242]
[70, 45, 1.0, 0.0, 3.292830228805542]
[70, 45, 1.5, 0.0, 3.409773349761963]
[70, 45, 2.0, 0.0, 4.002869367599487]
[70, 45, 2.5, 0.0, 4.8137664794921875]
[70, 45, 3.0, 0.0, 4.846220970153809]
[70, 45, 3.5, 0.30000000000000004, 3.7690279483795166]
[70, 45, 4.0, 0.0, 3.072498321533203]
[70, 45, 4.5, 0.7000000000000001, 4.765874147415161]
[70, 45, 5.0, 1.40

[75, 39, 2.0, 0.0, 3.186206817626953]
[75, 39, 2.5, 0.0, 3.2804462909698486]
[75, 39, 3.0, 0.0, 3.4973156452178955]
[75, 39, 3.5, 0.0, 3.7851390838623047]
[75, 39, 4.0, 0.6000000000000001, 4.006438970565796]
[75, 39, 4.5, 0.7000000000000001, 3.3680226802825928]
[75, 39, 5.0, 2.2, 3.276393175125122]
[75, 39, 10.0, 53.400000000000006, 3.2873878479003906]
[75, 42, 0.1, 0.0, 3.7695891857147217]
[75, 42, 0.3, 0.0, 4.688406705856323]
[75, 42, 1.0, 0.0, 4.30236554145813]
[75, 42, 1.5, 0.0, 3.9589850902557373]
[75, 42, 2.0, 0.0, 3.0848007202148438]
[75, 42, 2.5, 0.0, 3.674483299255371]
[75, 42, 3.0, 0.1, 3.2343950271606445]
[75, 42, 3.5, 0.1, 3.5835413932800293]
[75, 42, 4.0, 0.4, 3.2433393001556396]
[75, 42, 4.5, 1.1, 3.605652332305908]
[75, 42, 5.0, 1.6, 3.280280828475952]
[75, 42, 10.0, 54.2, 3.6324574947357178]
[75, 45, 0.1, 0.0, 3.6949703693389893]
[75, 45, 0.3, 0.0, 4.895248889923096]
[75, 45, 1.0, 0.0, 4.341467618942261]
[75, 45, 1.5, 0.0, 3.583477020263672]
[75, 45, 2.0, 0.0, 3.7383916

[80, 36, 10.0, 61.400000000000006, 3.481987237930298]
[80, 39, 0.1, 0.0, 4.856745719909668]
[80, 39, 0.3, 0.0, 4.145053863525391]
[80, 39, 1.0, 0.0, 3.6869328022003174]
[80, 39, 1.5, 0.0, 3.250986099243164]
[80, 39, 2.0, 0.0, 3.6450564861297607]
[80, 39, 2.5, 0.0, 3.2599401473999023]
[80, 39, 3.0, 0.1, 3.4601457118988037]
[80, 39, 3.5, 0.0, 3.47450590133667]
[80, 39, 4.0, 0.4, 3.305048704147339]
[80, 39, 4.5, 0.9, 3.5556576251983643]
[80, 39, 5.0, 1.6, 3.3936991691589355]
[80, 39, 10.0, 56.5, 4.109098434448242]
[80, 42, 0.1, 0.0, 5.49354100227356]
[80, 42, 0.3, 0.0, 4.061934471130371]
[80, 42, 1.0, 0.0, 3.7153236865997314]
[80, 42, 1.5, 0.0, 3.6503820419311523]
[80, 42, 2.0, 0.0, 3.7939071655273438]
[80, 42, 2.5, 0.0, 3.416957139968872]
[80, 42, 3.0, 0.0, 3.7170135974884033]
[80, 42, 3.5, 0.1, 3.434591770172119]
[80, 42, 4.0, 0.6000000000000001, 3.7239434719085693]
[80, 42, 4.5, 1.3, 3.530155897140503]
[80, 42, 5.0, 1.9000000000000001, 5.189182758331299]
[80, 42, 10.0, 55.1, 5.47748088

[85, 36, 4.0, 0.4, 3.2475478649139404]
[85, 36, 4.5, 1.3, 3.2762060165405273]
[85, 36, 5.0, 2.1, 3.466567039489746]
[85, 36, 10.0, 61.0, 3.719942092895508]
[85, 39, 0.1, 0.0, 4.044825553894043]
[85, 39, 0.3, 0.0, 3.976527690887451]
[85, 39, 1.0, 0.0, 3.588440179824829]
[85, 39, 1.5, 0.0, 4.969496011734009]
[85, 39, 2.0, 0.0, 3.7500433921813965]
[85, 39, 2.5, 0.0, 3.5135498046875]
[85, 39, 3.0, 0.0, 3.6603457927703857]
[85, 39, 3.5, 0.0, 3.523233652114868]
[85, 39, 4.0, 0.4, 3.4984848499298096]
[85, 39, 4.5, 1.4000000000000001, 3.674907922744751]
[85, 39, 5.0, 2.1, 3.964446783065796]
[85, 39, 10.0, 58.5, 4.113377809524536]
[85, 42, 0.1, 0.0, 4.465632200241089]
[85, 42, 0.3, 0.0, 4.058861494064331]
[85, 42, 1.0, 0.0, 3.779350519180298]
[85, 42, 1.5, 0.0, 3.9767227172851562]
[85, 42, 2.0, 0.0, 3.6274874210357666]
[85, 42, 2.5, 0.0, 3.8637874126434326]
[85, 42, 3.0, 0.0, 4.049153804779053]
[85, 42, 3.5, 0.0, 3.596604347229004]
[85, 42, 4.0, 0.30000000000000004, 4.033121824264526]
[85, 42, 

[90, 36, 2.5, 0.0, 3.5966060161590576]
[90, 36, 3.0, 0.0, 3.3504951000213623]
[90, 36, 3.5, 0.0, 3.3537652492523193]
[90, 36, 4.0, 0.4, 3.429333209991455]
[90, 36, 4.5, 0.8, 3.4066643714904785]
[90, 36, 5.0, 2.8000000000000003, 3.3571383953094482]
[90, 36, 10.0, 63.900000000000006, 3.2772207260131836]
[90, 39, 0.1, 0.0, 3.6132972240448]
[90, 39, 0.3, 0.0, 3.8132429122924805]
[90, 39, 1.0, 0.0, 4.43107795715332]
[90, 39, 1.5, 0.0, 4.235047817230225]
[90, 39, 2.0, 0.0, 4.1920716762542725]
[90, 39, 2.5, 0.0, 3.6365959644317627]
[90, 39, 3.0, 0.0, 3.5620102882385254]
[90, 39, 3.5, 0.0, 3.623727321624756]
[90, 39, 4.0, 0.5, 3.6212549209594727]
[90, 39, 4.5, 1.0, 3.628878355026245]
[90, 39, 5.0, 1.7000000000000002, 3.6541571617126465]
[90, 39, 10.0, 60.2, 3.6092846393585205]
[90, 42, 0.1, 0.0, 3.9271938800811768]
[90, 42, 0.3, 0.0, 4.411114692687988]
[90, 42, 1.0, 0.0, 4.5740966796875]
[90, 42, 1.5, 0.0, 4.566464900970459]
[90, 42, 2.0, 0.0, 3.9816293716430664]
[90, 42, 2.5, 0.0, 3.713418245

[95, 36, 1.0, 0.0, 3.8439791202545166]
[95, 36, 1.5, 0.0, 3.6565537452697754]
[95, 36, 2.0, 0.0, 3.6724777221679688]
[95, 36, 2.5, 0.0, 3.5770058631896973]
[95, 36, 3.0, 0.0, 3.7059326171875]
[95, 36, 3.5, 0.2, 3.6324357986450195]
[95, 36, 4.0, 0.7000000000000001, 3.6616311073303223]
[95, 36, 4.5, 1.0, 3.68263578414917]
[95, 36, 5.0, 2.7, 3.818639039993286]
[95, 36, 10.0, 67.5, 4.130603790283203]
[95, 39, 0.1, 0.0, 4.4477739334106445]
[95, 39, 0.3, 0.0, 4.275119066238403]
[95, 39, 1.0, 0.0, 3.8135650157928467]
[95, 39, 1.5, 0.0, 3.792036533355713]
[95, 39, 2.0, 0.0, 3.8957247734069824]
[95, 39, 2.5, 0.1, 3.8019425868988037]
[95, 39, 3.0, 0.1, 3.9511096477508545]
[95, 39, 3.5, 0.1, 3.8012213706970215]
[95, 39, 4.0, 0.30000000000000004, 3.8826639652252197]
[95, 39, 4.5, 0.7000000000000001, 4.028993606567383]
[95, 39, 5.0, 3.0, 4.2816712856292725]
[95, 39, 10.0, 62.5, 4.154988050460815]
[95, 42, 0.1, 0.0, 4.387842655181885]
[95, 42, 0.3, 0.0, 4.021474123001099]
[95, 42, 1.0, 0.0, 3.999106

[100, 33, 3.5, 0.1, 3.46753191947937]
[100, 33, 4.0, 1.1, 3.472402811050415]
[100, 33, 4.5, 1.5, 3.467857837677002]
[100, 33, 5.0, 2.8000000000000003, 3.4512157440185547]
[100, 33, 10.0, 69.8, 3.584580421447754]
[100, 36, 0.1, 0.0, 3.736737012863159]
[100, 36, 0.3, 0.0, 4.346852779388428]
[100, 36, 1.0, 0.0, 4.2397449016571045]
[100, 36, 1.5, 0.0, 4.346226215362549]
[100, 36, 2.0, 0.0, 3.8156509399414062]
[100, 36, 2.5, 0.0, 3.6831812858581543]
[100, 36, 3.0, 0.0, 3.780794143676758]
[100, 36, 3.5, 0.4, 3.673567295074463]
[100, 36, 4.0, 0.9, 3.6194357872009277]
[100, 36, 4.5, 1.2000000000000002, 3.6889278888702393]
[100, 36, 5.0, 4.0, 3.7245073318481445]
[100, 36, 10.0, 63.400000000000006, 3.6456379890441895]
[100, 39, 0.1, 0.0, 4.373866319656372]
[100, 39, 0.3, 0.0, 4.538678407669067]
[100, 39, 1.0, 0.0, 4.5463409423828125]
[100, 39, 1.5, 0.0, 4.032460689544678]
[100, 39, 2.0, 0.0, 3.9438180923461914]
[100, 39, 2.5, 0.0, 3.960139274597168]
[100, 39, 3.0, 0.0, 3.9993386268615723]
[100, 